export default {
	CHANGE_ZOOM: 'CHANGE_ZOOM',
	CHANGE_CENTER: 'CHANGE_CENTER',
	CHANGE_BOUNDS: 'CHANGE_BOUNDS',
	CHANGE_LAYERS: 'CHANGE_LAYERS',
	SELECT_FEATURE: 'SELECT_FEATURE',
	UNSELECT_FEATURE: 'UNSELECT_FEATURE',
	FIT_TO_FEATURE: 'FIT_TO_FEATURE'
};